### ISSUE TITLE
Set favicon

### ISSUE THREAD

**Issue by mstreit** [datavisyn/datavisyn.github.io#1]

**Comment by mstreit** [comment]
@chrilehner, can you please take care of this? Thanks.

**Comment by lehnerchristian** [comment]
sure. should I take the "d" or do we have a specific favicon?

**Comment by mstreit** [comment]
I think the d will look nice.

**Comment by lehnerchristian** [comment]
c428c8be0a6037e4919368f7a02a369d842c9cb6
