### ISSUE TITLE
Links for Nils' profiles

### ISSUE THREAD

**Issue by alexsb** [datavisyn/datavisyn.github.io#10]
Both Sam and Nils have a personal website - the link is missing.

**Comment by sgratzl** [comment]
on purpose

**Comment by alexsb** [comment]
And what's the purpose?

**Comment by sgratzl** [comment]
I mean I didn't add my website because I don't see a reason to do so.

**Comment by alexsb** [comment]
Adding a link to your website underscores your credibility and shows that you're an expert in the technology we're selling.
