### ISSUE TITLE
Fix formating for target discovery platform

### ISSUE THREAD

**Issue by alexsb** [datavisyn/datavisyn.github.io#12]
This doesn't look so great: 

![image](https://user-images.githubusercontent.com/2039375/28884405-edb1b5b8-776e-11e7-97aa-57e12641618a.png)

Simple fix would be to limit the width of the main text above the screenshot.

**Comment by sgratzl** [comment]
part of https://github.com/datavisyn/datavisyn.github.io/pull/28
