### ISSUE TITLE
Add dashboard app to website

### ISSUE THREAD

**Issue by mstreit** [datavisyn/datavisyn.github.io#24]

**Comment by sgratzl** [comment]
aka dTiles

**Comment by sluger** [comment]
![dashboards](https://user-images.githubusercontent.com/5220584/33840859-6207b50a-de96-11e7-9da3-22d5e74ef9b0.png)

**Comment by sluger** [comment]
What do you think about changing the carousel to static images that show our Ordino and dTiles application with an attached feature list. see: https://docs.google.com/a/datavisyn.io/drawings/d/1VtEvJtUu8rHW3NXroXuSw-kTXk7WKlMZRJ2poA-K4Dk/edit?usp=sharing

**Comment by sluger** [comment]
![image](https://user-images.githubusercontent.com/5220584/34110140-07edf8d4-e406-11e7-8f0e-0102a081a8dd.png)

**Comment by lehnerchristian** [comment]
we need another screenshot with the name dTiles + datavisyn "d" logo instead of Target360

**Comment by sluger** [comment]
![dashboards](https://user-images.githubusercontent.com/5220584/34202940-9f1b17ea-e579-11e7-9b0e-8482c43c07d2.png)

**Comment by lehnerchristian** [comment]
nice, thanks!

**Comment by lehnerchristian** [comment]
dTiles is added in the https://github.com/datavisyn/datavisyn.github.io/tree/website_fixes branch. The content needs to be edited in the GDocs file
