### ISSUE TITLE
add note that academic licenses are available

### ISSUE THREAD

**Issue by sgratzl** [datavisyn/datavisyn.github.io#27]

**Comment by sgratzl** [comment]
@mstreit what should be the exact text?

**Comment by mstreit** [comment]
Academic licenses for research or educational use can be obtained free of charge. To request an academic license, please send an email to contact@datavisyn.io.

@ngehlenborg @alexsb, please check the text and let us know if you want to formulate it differently.

**Comment by alexsb** [comment]
Sounds good.

**Comment by lehnerchristian** [comment]
where should we put this information on the website? do we have a pricing scheme, which we want to publish on the website?
or should it just be a hint somewhere near the contact section?

**Comment by alexsb** [comment]
I'd put it at the end of the product section: 

![image](https://user-images.githubusercontent.com/2039375/32855826-265070ce-ca00-11e7-8af2-239b225930f3.png)

Also extend this to:

> For licensing details and pricing please send an e-mail to contact@datavisyn.io. 
Academic licenses for research or educational use can be obtained free of charge. To request an academic license write to contact@datavisyn.io.

**Comment by mstreit** [comment]
Sounds good. Thanks for the input @alexsb.

**Comment by lehnerchristian** [comment]
What about the following?

> Academic licenses for research or educational use can be obtained free of charge. To request an academic license or to get details and pricing please send an e-mail to contact@datavisyn.io.

Then we would have the "send an e-mail to" part only once.

**Comment by lehnerchristian** [comment]
This lives currently in the following branch: https://github.com/datavisyn/datavisyn.github.io/tree/website_fixes

and looks like this:
![screenshot from 2017-11-21 17-14-46](https://user-images.githubusercontent.com/1711080/33083401-8ff4a7e6-cedf-11e7-8914-7db5ac2fa456.png)


or do we prefer this version for the moment?
![screenshot from 2017-11-21 17-17-35](https://user-images.githubusercontent.com/1711080/33083557-f2523368-cedf-11e7-8a3a-5fabb14e5e5f.png)

**Comment by lehnerchristian** [comment]
the first version centered doesn't looks weird in my opinion.
![screenshot from 2017-11-21 17-19-57](https://user-images.githubusercontent.com/1711080/33083646-39a7f91e-cee0-11e7-95b3-55bb3c76c059.png)

@mstreit , what do you say?

**Comment by alexsb** [comment]
I prefer the version with the e-mail address only once.

**Comment by mstreit** [comment]
I agree with alex.
