### ISSUE TITLE
add affiliations to founders pics

### ISSUE THREAD

**Issue by sgratzl** [datavisyn/datavisyn.github.io#30]
professor at HMS, JKU, Utah, ...

**Comment by lehnerchristian** [comment]
link to labs (e.g. gehlenborglab) in new tab

**Comment by sluger** [comment]
http://gehlenborglab.org/
http://vdl.sci.utah.edu/team/lex/
https://www.jku.at/en/institute-of-computer-graphics/

**Comment by sluger** [comment]
christian introduces jekyll to stefan
