### ISSUE TITLE
update dTiles screenshots

### ISSUE THREAD

**Issue by sgratzl** [datavisyn/datavisyn.github.io#38]
are outdated

**Comment by sgratzl** [comment]
with the new branch, please also create thumbnails

big size: 1920 x 1080 png
large thumbnail: 600 x ? progressive jpg
small thumbnail: 200 x ? progressive jpg

**Comment by sluger** [comment]
with gimp2, the progressive jpg export at around 40% of the size is really ugly compared to the original png:
![image](https://user-images.githubusercontent.com/5220584/40416626-0523ccb2-5e7e-11e8-9aea-bfd7cc0fbbf2.png)

**Comment by sluger** [comment]
has the issue been sorted already, im not sure and this ticket is blocked by it

**Comment by sluger** [comment]
the issue that not scores were displayed in lineup is fixed so this issue isnt blocked anymore

**Comment by sgratzl** [comment]
@sluger ping

**Comment by sgratzl** [comment]
moved to trello
