### ISSUE TITLE
Implement feedback

### ISSUE THREAD

**Issue by lehnerchristian** [datavisyn/datavisyn.github.io#40]
- fehlt ein pounkt nach dem ersten absatz
- bei den benefits wuerd ich das anders anordnen
- Flexible work hours -> home office possible
- der rest ist mmn eher nicht so relevant?
- Partially home office possible -> Work remotely for a part of your time
- Used to work with source code management systems -> Source code management systems [konsistent mit anderen punkten]
- Relational, -> relational
- used to business design tools (such as Inkscape) -> graphic design tools
- Tools: Github: Issue flow, Git, branch concept -> remove
- Excellent knowledge of German and English -> German ist notwendig?

**Comment by sgratzl** [comment]
any status update?

**Comment by lehnerchristian** [comment]
yes, I've merged it in https://github.com/datavisyn/datavisyn.github.io/commit/65af0b8215a426569d71fb6d2de7391c2592aff6
therefore I'll close the issue
