### ISSUE TITLE
add anita to website

### ISSUE THREAD

**Issue by sgratzl** [datavisyn/datavisyn.github.io#43]

**Comment by lehnerchristian** [comment]
I also thought about this some days ago. what exactly is the job description we should use?
and which image, @anita-steiner ?
should we link to social media profiles or a personal website?

**Comment by mstreit** [comment]
job title: Project Manager

**Comment by mstreit** [comment]
@anita-steiner, please send an image to @lehnerchristian. your name should be on the website soon.

**Comment by lehnerchristian** [comment]
@anita-steiner , please send it to @sluger

**Comment by sgratzl** [comment]
moved
