### ISSUE TITLE
benefits layout broken

### ISSUE THREAD

**Issue by lehnerchristian** [datavisyn/datavisyn.github.io#46]
I think this used to be 3 items per row. somehow the layout is broken to be 4 items in the first row and 2 in the second one

![datavisyn_io_broken_layout](https://user-images.githubusercontent.com/1711080/45803212-4953cb00-bcb9-11e8-976f-f233c56f4b9f.png)

**Comment by sgratzl** [comment]
https://github.com/datavisyn/datavisyn.github.io/blob/643b046869511a944bd1391f76b82140499566b3/_sass/_mixins.scss#L2-L13

declare that at screens > 992px an element should use just 25%, there are 6 items, so four int the first one, and 2 in the second

https://github.com/datavisyn/datavisyn.github.io/blob/643b046869511a944bd1391f76b82140499566b3/_sass/jobs.scss#L5

declares that spacing wise the space should be distributed between items -> the two are on the sides and space is between in the second row. `space-around` or `space-evenly` would be an option
