### ISSUE TITLE
Move Partner logos to the footer and rename the current "Partners" section to customers?

### ISSUE THREAD

**Issue by lehnerchristian** [datavisyn/datavisyn.github.io#66]
having the partners, such as Tech2b, etc. next to the customers is not ideal, because sometimes the partners have requirements which require us to style them specially whereas customers can be treated uniformly.

maybe we should move the partners to the footer and make the "Partners" section a "Customers" section?

**Comment by mstreit** [comment]
Hi @lehnerchristian, what do you mean by `style them specifically`? I've checked the version that is online and it looks good to me.
